backend:
  name: git-gateway
  repo: ladderstack/dreamly-gatsby
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: "Press"
    label: "Press"
    folder: "content/press"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: title
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "press",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
  - name: "Members"
    label: "Members"
    folder: "content/members"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: title
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "members",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Job Title", name: "job-title", widget: "string" }
      - { label: "Jap Name", name: "jap-name", widget: "string" }
      - { label: "Profile Picture", name: "profile-pic", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Skills", name: "skills", widget: "string" }
      - { label: "Small Image", name: "smallImage", widget: "image" }
      - label: SNS
        name: SNS
        widget: object
        fields:
          - { label: "facebook", name: "facebook", widget: string }
          - { label: "twitter", name: "twitter", widget: string }
          - { label: "github", name: "github", widget: string }
          - { label: "linkedin", name: "linkedin", widget: string }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.json"
        fields:
          - { label: Vision, name: vision, widget: string }
          - {
              label: Vision Description,
              name: visionDescription,
              widget: markdown,
            }
          - { label: Mission, name: mission, widget: string }
          - {
              label: Mission Description,
              name: missionDescription,
              widget: markdown,
            }
          - { label: Message From CEO, name: message_ceo, widget: markdown }
          - label: Company Profile
            name: companyprofile
            widget: "object"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Setup, name: setup, widget: string }
              - { label: Capital, name: capital, widget: string }
              - {
                  label: Business content,
                  name: business_content,
                  widget: string,
                }
              - { label: Representative, name: representative, widget: string }
              - { label: Location, name: location, widget: string }
              - {
                  label: Number of Employess,
                  name: number-employees,
                  widget: string,
                }
              - label: "SNS"
                name: "SNS"
                widget: object
                fields:
                  - { label: "Facebook", name: "facebook", widget: string }
                  - { label: "Twitter", name: "twitter", widget: string }
                  - { label: "Github", name: "github", widget: string }
              - label: "Consultant"
                name: "consultant"
                widget: "object"
                fields:
                  - {
                      label: "General Advisor",
                      name: "generaladvisor",
                      widget: "string",
                    }
                  - {
                      label: "Consultant tax accountant",
                      name: "consultanttax",
                      widget: "string",
                    }
                  - {
                      label: "Advisor company labor and social security attorney",
                      name: "advisor-company",
                      widget: "string",
                    }
                  - {
                      label: "General Counsel",
                      name: "general-counsel",
                      widget: "string",
                    }
                  - {
                      label: "Design Advisor",
                      name: "design-advisor",
                      widget: "string",
                    }
                  - {
                      label: "Agile Advisor",
                      name: "agile-advisor",
                      widget: "string",
                    }
      - label: "Recruitment Page"
        name: "Recruitment"
        file: "content/recruitment.json"
        fields:
          - { label: Title, name: title, widget: string }
          - label: "Sub Heading"
            name: "subheading"
            widget: "object"
            fields:
              - { label: English Text, name: engtext, widget: string }
              - { label: Jap Text, name: japtext, widget: string }
              - { label: Description, name: description, widget: string }
          - label: "Core Values"
            name: "corevalues"
            widget: "list"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Jap Heading, name: japheading, widget: string }
              - { label: Description, name: description, widget: string }
          - label: "5 likes"
            name: "fivelikes"
            widget: "list"
            fields:
              - { label: Description, name: description, widget: markdown }
          - { label: Job Link, name: joblink, widget: string }
      - label: "Home"
        name: "Home"
        file: "content/home.json"
        fields:
          - { label: Title, name: title, widget: string }
          - label: "Hero Image"
            name: "heroimage"
            widget: "object"
            fields:
              - { label: image, name: image, widget: image }
              - { label: Heading, name: heading, widget: string }
              - { label: Description, name: description, widget: markdown }
          - label: "About Dreamly"
            name: "aboutDreamly"
            widget: "object"
            fields:
              - { label: Description, name: description, widget: markdown }
              - { label: More Link, name: moreLink, widget: string }
              - label: "Slider Images"
                name: "sliderImages"
                widget: "list"
                fields:
                  - { label: Slider Title, name: sliderTitle, widget: string }
                  - { label: Image, name: image, widget: image }
          - label: "What We Do"
            name: "whatWeDo"
            widget: "object"
            fields:
              - { label: Description, name: description, widget: markdown }
              - { label: More Link, name: moreLink, widget: string }
              - label: "Slider Images"
                name: "sliderImages"
                widget: "list"
                fields:
                  - { label: Slider Title, name: sliderTitle, widget: string }
                  - { label: Image, name: image, widget: image }
          - label: "Do Something"
            name: "doSomething"
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Link, name: link, widget: string }
