backend:
  name: github
  repo: ladderstack/dreamly-gatsby
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: "Members"
    label: "Members"
    folder: "site/content/members"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Job Title", name: "job-title", widget: "string" }
      - { label: "Title", name: "Title", widget: "string" }
      - { label: "Jap Name", name: "jap-name", widget: "string" }
      - { label: "Profile Picture", name: "profile-pic", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Skills", name: "skills", widget: "string" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "site/content/about.yml"
        fields:
          - { label: Vision, name: vision, widget: string }
          - { label: Mission, name: mission, widget: string }
          - { label: Message From CEO, name: message_ceo, widget: markdown }
          - label: Company Profile
            name: companyprofile
            widget: "object"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Setup, name: setup, widget: string }
              - { label: Capital, name: capital, widget: string }
              - {
                  label: Business content,
                  name: business_content,
                  widget: string,
                }
              - { label: Representative, name: representative, widget: string }
              - { label: Location, name: location, widget: string }
              - {
                  label: Number of Employess,
                  name: number-employees,
                  widget: string,
                }
              - label: "SNS"
                name: "SNS"
                widget: object
                fields:
                  - { label: "Facebook", name: "facebook", widget: string }
                  - { label: "Twitter", name: "twitter", widget: string }
                  - { label: "Github", name: "github", widget: string }
              - label: "Consultant"
                name: "consultant"
                widget: "object"
                fields:
                  - {
                      label: "General Advisor",
                      name: "generaladvisor",
                      widget: "string",
                    }
                  - {
                      label: "Consultant tax accountant",
                      name: "consultanttax",
                      widget: "string",
                    }
                  - {
                      label: "Advisor company labor and social security attorney",
                      name: "advisor-company",
                      widget: "string",
                    }
                  - {
                      label: "General Counsel",
                      name: "general-counsel",
                      widget: "string",
                    }
                  - {
                      label: "Design Advisor",
                      name: "design-advisor",
                      widget: "string",
                    }
                  - {
                      label: "Agile Advisor",
                      name: "agile-advisor",
                      widget: "string",
                    }
      - label: "Recruitment Page"
        name: "Recruitment"
        file: "site/content/recruitment.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - label: "Sub Heading"
            name: "sub-heading"
            widget: "object"
            fields:
              - { label: English Text, name: eng-text, widget: string }
              - { label: Jap Text, name: jap-text, widget: string }
              - { label: Description, name: description, widget: string }
          - label: "Core Values"
            name: "core-values"
            widget: "list"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Jap Heading, name: jap-heading, widget: string }
              - { label: Description, name: description, widget: string }
          - label: "5 likes"
            name: "five-likes"
            widget: "list"
            fields:
              - { label: Heading, name: heading, widget: markdown }
              - { label: Image, name: image, widget: image }
              - { label: Description, name: description, widget: string }
          - { label: Job Link, name: job-link, widget: string }
